### ISSUE TITLE
[Bug] 2.5.1 does not compile for iOS: 'value(forHTTPHeaderField:)' requires iOS 13, package declares .iOS(.v12)

### ISSUE THREAD

**Issue by AnderGoig** [Unleash/unleash-ios-sdk#140]
## Summary

`2.5.1` fails to compile for any iOS consumer. `Poller.swift` uses `HTTPURLResponse.value(forHTTPHeaderField:)`, introduced in iOS 13.0 / macOS 10.15, while `Package.swift` still declares `.iOS(.v12)`.

```
Sources/UnleashProxyClientSwift/Poller/Poller.swift:206:43: error: 'value(forHTTPHeaderField:)' is only available in iOS 13.0 or newer
```

Introduced by #137 (case-insensitive etag lookup), released in 2.5.1. `main` has the same code, so 2.5.0 is currently the last version that builds for iOS.

## Reproduction

Against tag `2.5.1`:

```sh
git clone --depth 1 --branch 2.5.1 https://github.com/Unleash/unleash-ios-sdk
cd unleash-ios-sdk

swift build
# Build complete! (8.78s)

xcodebuild -scheme UnleashProxyClientSwift -destination 'generic/platform=iOS' build
# Poller.swift:206:43: error: 'value(forHTTPHeaderField:)' is only available in iOS 13.0 or newer
```

Also reproduces when the package is consumed from an Xcode project targeting an iOS simulator.

## Why CI did not catch it

All three jobs in `.github/workflows/build.yml` run `swift build` / `swift test` on `macos-latest`, which compiles for the host platform. Against the declared `.macOS(.v10_15)` minimum the API is exactly available, so the build passes. No job ever compiles against the `.iOS(.v12)` minimum, so the availability violation is invisible.

## Suggested fix

Either:

- raise the declared platform to `.iOS(.v13)` (and `.macOS(.v10_15)` already matches), or
- read the header via `allHeaderFields` with a case-insensitive lookup, keeping the iOS 12 floor.

Plus a CI job that builds for an iOS destination, so the declared minimum is actually exercised.

**Comment by sighphyre** [comment]
>Apologies for the issue. I've opened a potential PR to fix this.

I think this is on me, actually, CI should have caught this. I've added a check so that this doesn't happen again. Thanks for the fix here!

**Comment by sighphyre** [comment]
Can't really do anything about 2.5.1 now since that's released, but this is fixed in 2.5.2, appreciate the report here!
